import login1 from '../assets/login.jpg'
import login2 from '../assets/login2.jpg';
import login3 from '../assets/login3.jpg';

export const carouselImages = [
    {
      src: login1,
      alt: 'Imagen 1',
      quote: "Nuestra empresa es líder en innovación. Juntos, transformamos el futuro.",
      author: "Betsabe Hoyos",
      position: "CEO, Gestor de personal",
    },
    {
      src: login2,
      alt: 'Imagen 2',
      quote: "Cambiamos el mundo a través de la tecnología y el compromiso.",
      author: "Luis Martínez",
      position: "CTO, Innovación Tech",
    },
    {
      src: login3,
      alt: 'Imagen 3',
      quote: "La excelencia y la innovación son nuestros pilares.",
      author: "Ana García",
      position: "COO, Tech Global",
    },
  ];